from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QCheckBox, QComboBox, QFrame, QGridLayout, QHBoxLayout, QLabel, QPlainTextEdit, QPushButton,
    QListView, QScrollArea, QSizePolicy, QSpinBox, QStackedWidget, QTableWidget, QVBoxLayout, QWidget
)

from mvc.View.Componentes.componentes import MetricStrip


class Bc250Frame:
    def __init__(self, vista):
        self.vista = vista
        self.contenedor = self._forms()

    def _forms(self):
        v = self.vista
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(8)
        top = v.titulo_pagina('BC250', 'Metricas en tiempo real arriba; abajo cambias entre GPU, CPU y 40CU sin salir de esta vista.')
        v.placa_pill = QLabel('--')
        v.placa_pill.setObjectName('InfoPill')
        v.placa_pill.setAlignment(Qt.AlignmentFlag.AlignCenter)
        top.addWidget(v.placa_pill)
        layout.addLayout(top)

        hero = QFrame()
        hero.setObjectName('BcHero')
        hero_layout = QVBoxLayout(hero)
        hero_layout.setContentsMargins(12, 8, 12, 8)
        hero_layout.setSpacing(5)
        hero_title = QHBoxLayout()
        hero_name = QLabel('Monitor BC250')
        hero_name.setObjectName('SectionTitle')
        hero_desc = QLabel('CPU, GPU, governor y memoria de video en vivo')
        hero_desc.setObjectName('Muted')
        hero_title.addWidget(hero_name)
        hero_title.addWidget(hero_desc)
        hero_title.addStretch(1)
        preparar = QPushButton('Preparar dependencias')
        preparar.setToolTip('Instalar/clonar herramientas faltantes para BC250')
        preparar.clicked.connect(v.instalar_dependencias_bc250)
        activar_governor = QPushButton('Activar governor')
        activar_governor.setToolTip('Ejecuta systemctl enable --now cyan-skillfish-governor-smu')
        activar_governor.clicked.connect(lambda: v.controlar_governor('activar'))
        desactivar_governor = QPushButton('Desactivar governor')
        desactivar_governor.setToolTip('Ejecuta systemctl disable --now cyan-skillfish-governor-smu')
        desactivar_governor.clicked.connect(lambda: v.controlar_governor('desactivar'))
        hero_title.addWidget(preparar)
        hero_title.addWidget(activar_governor)
        hero_title.addWidget(desactivar_governor)
        hero_layout.addLayout(hero_title)

        metricas = QGridLayout()
        metricas.setSpacing(6)
        v.bc_cpu_mhz = MetricStrip('CPU MHz', '#2563eb')
        v.bc_cpu_temp = MetricStrip('CPU temp', '#dc2626')
        v.bc_cpu_volt = MetricStrip('CPU voltaje', '#d97706')
        v.bc_sclk = MetricStrip('GPU SCLK / Volt', '#ea580c')
        v.bc_gpu_temp = MetricStrip('GPU temp / PPT', '#be123c')
        v.bc_servicio = MetricStrip('Governor', '#16a34a')
        v.bc_rango = MetricStrip('Rango GPU', '#0ea5e9')
        v.bc_vram = MetricStrip('VRAM', '#7c3aed')
        for i, w in enumerate([
            v.bc_cpu_mhz, v.bc_cpu_temp, v.bc_cpu_volt, v.bc_sclk,
            v.bc_gpu_temp, v.bc_servicio, v.bc_rango, v.bc_vram
        ]):
            w.spark.setVisible(False)
            w.detalle.setFixedHeight(15)
            w.setMaximumHeight(58)
            w.setMinimumWidth(0)
            w.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
            metricas.addWidget(w, i // 4, i % 4)
        hero_layout.addLayout(metricas)
        layout.addWidget(hero)

        selector = QFrame()
        selector.setObjectName('SegmentBar')
        sl = QHBoxLayout(selector)
        sl.setContentsMargins(10, 6, 10, 6)
        sl.setSpacing(7)
        titulo = QLabel('Panel BC250')
        titulo.setObjectName('SectionTitle')
        sl.addWidget(titulo)
        v.bc_mode_buttons = []
        for idx, texto in enumerate(['GPU', 'CPU', '40CU']):
            btn = QPushButton(texto)
            btn.setCheckable(True)
            btn.clicked.connect(lambda _=False, i=idx: v.cambiar_bc_panel(i))
            v.bc_mode_buttons.append(btn)
            sl.addWidget(btn)
        sl.addStretch(1)
        layout.addWidget(selector)

        v.bc_panel_stack = QStackedWidget()
        v.bc_panel_stack.addWidget(self._panel_gpu())
        v.bc_panel_stack.addWidget(self._panel_cpu())
        v.bc_panel_stack.addWidget(self._panel_40cu())
        layout.addWidget(v.bc_panel_stack, 1)
        v.cambiar_bc_panel(0)
        return page


    def _panel_con_scroll(self, page):
        outer = QWidget()
        outer.setObjectName('ScrollOuter')
        outer.setAttribute(Qt.WidgetAttribute.WA_StyledBackground, True)
        outer_layout = QVBoxLayout(outer)
        outer_layout.setContentsMargins(0, 0, 0, 0)
        scroll = QScrollArea()
        scroll.setObjectName('FlatScroll')
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QFrame.Shape.NoFrame)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        scroll.viewport().setAutoFillBackground(False)
        scroll.viewport().setStyleSheet('background: transparent;')
        page.setAttribute(Qt.WidgetAttribute.WA_StyledBackground, True)
        scroll.setWidget(page)
        outer_layout.addWidget(scroll)
        return outer


    def _panel_perfiles(self):
        v = self.vista
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(10)

        aviso = QLabel('Perfiles inteligentes conservadores: aplican rangos GPU validados. No activan 40CU ni CPU OC automaticamente.')
        aviso.setObjectName('WarningTextCompact')
        aviso.setWordWrap(True)
        layout.addWidget(aviso)

        grid = QGridLayout()
        grid.setSpacing(8)
        perfiles = [
            ('Seguro', '500-1500 MHz, recomendado para estabilidad diaria.', 'seguro'),
            ('Gaming', '1000-1850 MHz, buen balance para juegos.', 'gaming'),
            ('40CU recomendado', '500/1000-1500 MHz antes de probar 40CU.', 'cu40'),
            ('Benchmark controlado', '1000-2000 MHz con advertencia de riesgo.', 'benchmark'),
            ('Recuperacion', '500-1000 MHz para bajar carga y estabilizar.', 'recuperacion'),
        ]
        for i, (titulo, detalle, clave) in enumerate(perfiles):
            box = QFrame()
            box.setObjectName('InfoBox')
            bl = QVBoxLayout(box)
            bl.setContentsMargins(12, 10, 12, 10)
            bl.setSpacing(6)
            label = QLabel(v.t(titulo))
            label.setObjectName('SectionTitle')
            desc = QLabel(v.t(detalle))
            desc.setObjectName('Muted')
            desc.setWordWrap(True)
            btn = QPushButton(f'{v.t("Aplicar")} {v.t(titulo)}')
            if clave in ['benchmark']:
                btn.setObjectName('DangerButton')
            btn.clicked.connect(lambda _=False, c=clave: v.aplicar_perfil_inteligente(c))
            bl.addWidget(label)
            bl.addWidget(desc)
            bl.addStretch(1)
            bl.addWidget(btn)
            grid.addWidget(box, i // 2, i % 2)
        layout.addLayout(grid, 1)
        return page


    def _panel_gpu(self):
        v = self.vista
        page = QWidget()
        page.setObjectName('ScrollPage')
        layout = QVBoxLayout(page)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(8)

        panel = QFrame()
        panel.setObjectName('BcPanel')
        pl = QVBoxLayout(panel)
        pl.setContentsMargins(12, 10, 12, 10)
        pl.setSpacing(10)

        head = QHBoxLayout()
        title = QLabel('GPU')
        title.setObjectName('SectionTitle')
        hint = QLabel('Control de rango, piso de frecuencia y laboratorio de voltaje')
        hint.setObjectName('Muted')
        head.addWidget(title)
        head.addWidget(hint)
        head.addStretch(1)
        v.gpu_oc_experimental = QCheckBox('Mostrar OC alto')
        v.gpu_oc_experimental.setToolTip('Muestra frecuencias altas y permite laboratorio de undervolt controlado')
        v.gpu_oc_experimental.stateChanged.connect(lambda _=0: v.actualizar_bc250(silencioso=True))
        head.addWidget(v.gpu_oc_experimental)
        pl.addLayout(head)

        min_box = QFrame()
        min_box.setObjectName('InfoBox')
        ml = QHBoxLayout(min_box)
        ml.setContentsMargins(10, 8, 10, 8)
        ml.setSpacing(7)
        min_title = QLabel('Piso GPU')
        min_title.setObjectName('SectionTitle')
        min_hint = QLabel('Fuerza un mínimo para juegos livianos que no despiertan el governor')
        min_hint.setObjectName('Muted')
        ml.addWidget(min_title)
        ml.addWidget(min_hint)
        ml.addStretch(1)
        v.gpu_min_buttons = []
        for valor in (500, 1000, 2000):
            bmin = QPushButton(f'{valor} MHz')
            bmin.setCheckable(True)
            bmin.setProperty('minimo', valor)
            bmin.clicked.connect(lambda _=False, minimo=valor: v.cambiar_gpu_minimo_aplicado(minimo))
            v.gpu_min_buttons.append(bmin)
            ml.addWidget(bmin)
        v.set_gpu_minimo(v.gpu_minimo)
        pl.addWidget(min_box)

        perfil_box = QFrame()
        perfil_box.setObjectName('InfoBox')
        perfil_layout = QGridLayout(perfil_box)
        perfil_layout.setContentsMargins(10, 8, 10, 8)
        perfil_layout.setHorizontalSpacing(7)
        perfil_layout.setVerticalSpacing(7)
        v.gpu_max_config_freq = 1500
        perfiles_gpu = [
            ('Eco', '500/1000 -> 1000 MHz', 1000, False),
            ('Recomendado', '1500 MHz', 1500, False),
            ('Alto', '1850 MHz', 1850, False),
            ('Muy alto', '2000 MHz', 2000, False),
        ]
        v.gpu_profile_buttons = []
        for i, (titulo, detalle, freq, es_max) in enumerate(perfiles_gpu):
            card = QFrame()
            card.setObjectName('DetailChip')
            card.setMinimumHeight(74)
            card.setMaximumHeight(82)
            cl = QHBoxLayout(card)
            cl.setContentsMargins(10, 8, 10, 8)
            cl.setSpacing(8)
            textos = QVBoxLayout()
            textos.setContentsMargins(0, 0, 0, 0)
            textos.setSpacing(2)
            label = QLabel(v.t(titulo))
            label.setObjectName('SectionTitle')
            desc = QLabel(v.t(detalle))
            desc.setObjectName('Muted')
            btn = QPushButton(f'{v.t("Aplicar")} {freq}')
            btn.setObjectName('ApplyButton')
            btn.setMinimumHeight(38)
            btn.setMinimumWidth(118)
            btn.clicked.connect(lambda _=False, f=freq, t=titulo, m=es_max: v.aplicar_perfil_bc250(
                v.minimo_gpu_seleccionado(),
                v.gpu_max_config_freq if m else f,
                f'Max TOML {v.gpu_max_config_freq}' if m else t
            ))
            btn.setProperty('freq', freq)
            btn.setProperty('dynamic_max', es_max)
            v.gpu_profile_buttons.append(btn)
            textos.addWidget(label)
            textos.addWidget(desc)
            cl.addLayout(textos, 1)
            cl.addWidget(btn)
            perfil_layout.addWidget(card, 0, i)
        pl.addWidget(perfil_box)

        tools = QFrame()
        tools.setObjectName('InfoBox')
        tl = QHBoxLayout(tools)
        tl.setContentsMargins(10, 8, 10, 8)
        tl.setSpacing(7)
        lab_title = QLabel('OC avanzado')
        lab_title.setObjectName('SectionTitle')
        lab_hint = QLabel('Ajustes por safe-points existentes del TOML')
        lab_hint.setObjectName('Muted')
        v.gpu_risk_combo = QComboBox()
        v.gpu_risk_combo.setObjectName('RiskCombo')
        v.gpu_risk_combo.setMinimumWidth(146)
        risk_popup = QListView()
        risk_popup.setObjectName('RiskComboPopup')
        risk_popup.viewport().setObjectName('RiskComboPopupViewport')
        risk_popup.setAutoFillBackground(True)
        risk_popup.viewport().setAutoFillBackground(True)
        risk_popup.setAlternatingRowColors(False)
        risk_popup.setUniformItemSizes(True)
        risk_popup.setMinimumWidth(146)
        risk_popup.setStyleSheet(v.estilo_risk_popup())
        v.gpu_risk_combo.setView(risk_popup)
        v.gpu_risk_combo.setToolTip('Frecuencias altas tomadas de safe-points validos del TOML')
        v.gpu_risk_apply = QPushButton('Aplicar OC')
        v.gpu_risk_apply.setObjectName('DangerButton')
        v.gpu_risk_apply.clicked.connect(v.aplicar_gpu_riesgo_combo)
        status_governor = QPushButton('Status governor')
        status_governor.setToolTip('Muestra systemctl status cyan-skillfish-governor-smu sin abrir terminal')
        status_governor.clicked.connect(v.mostrar_status_governor)
        lab_voltaje = QPushButton('Lab voltaje')
        lab_voltaje.setToolTip('Abre una ventana para probar curvas GPU por niveles de +10 mV')
        lab_voltaje.clicked.connect(v.abrir_laboratorio_voltaje_gpu)
        tl.addWidget(lab_title)
        tl.addWidget(lab_hint)
        tl.addStretch(1)
        tl.addWidget(v.gpu_risk_combo)
        tl.addWidget(v.gpu_risk_apply)
        tl.addWidget(status_governor)
        tl.addWidget(lab_voltaje)
        pl.addWidget(tools)

        layout.addWidget(panel)

        texto_gpu = v.t('Advertencia: la app no modifica el TOML salvo que uses Lab voltaje. Cambia frecuencias sin carga 3D activa.')
        v.alerta_oc = QLabel(v.alerta_gpu_html(texto_gpu))
        v.alerta_oc.setObjectName('WarningTextCompact')
        v.alerta_oc.setWordWrap(True)
        v.alerta_oc.setOpenExternalLinks(True)
        v.alerta_oc.setTextFormat(Qt.TextFormat.RichText)
        layout.addWidget(v.alerta_oc)

        detalle = QFrame()
        detalle.setObjectName('BcDetailPanel')
        detalle_layout = QVBoxLayout(detalle)
        detalle_layout.setContentsMargins(12, 10, 12, 10)
        detalle_layout.setSpacing(7)
        titulo_detalle = QLabel('Estado detallado GPU')
        titulo_detalle.setObjectName('SectionTitle')
        detalle_layout.addWidget(titulo_detalle)

        resumen = QGridLayout()
        resumen.setHorizontalSpacing(8)
        resumen.setVerticalSpacing(5)
        v.bc_detail_labels = {}
        campos = [
            ('service', 'Governor'), ('dbus', 'D-Bus'), ('range', 'Rango'),
            ('sclk', 'SCLK'), ('volt', 'Voltaje'), ('busy', 'Carga'),
            ('driver', 'Driver'), ('config', 'Config')
        ]
        for i, (clave, titulo_campo) in enumerate(campos):
            item = QFrame()
            item.setObjectName('DetailChip')
            item_layout = QVBoxLayout(item)
            item_layout.setContentsMargins(8, 5, 8, 5)
            item_layout.setSpacing(0)
            nombre = QLabel(titulo_campo)
            nombre.setObjectName('Muted')
            valor = QLabel('--')
            valor.setObjectName('DetailValue')
            valor.setWordWrap(True)
            item_layout.addWidget(nombre)
            item_layout.addWidget(valor)
            v.bc_detail_labels[clave] = valor
            resumen.addWidget(item, i // 4, i % 4)
        detalle_layout.addLayout(resumen)

        v.bc_safe_points_text = QPlainTextEdit()
        v.bc_safe_points_text.setObjectName('TerminalText')
        v.bc_safe_points_text.setReadOnly(True)
        v.bc_safe_points_text.setMinimumHeight(100)
        v.bc_safe_points_text.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        detalle_layout.addWidget(v.bc_safe_points_text, 1)
        layout.addWidget(detalle, 1)
        return self._panel_con_scroll(page)


    def _panel_cpu(self):
        v = self.vista
        page = QWidget()
        page.setObjectName('ScrollPage')
        layout = QVBoxLayout(page)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(8)

        panel = QFrame()
        panel.setObjectName('BcPanel')
        pl = QVBoxLayout(panel)
        pl.setContentsMargins(12, 10, 12, 10)
        pl.setSpacing(9)

        head = QHBoxLayout()
        title = QLabel('CPU OC temporal')
        title.setObjectName('SectionTitle')
        hint = QLabel('Perfiles y laboratorio seguro para bc250-detect --keep')
        hint.setObjectName('Muted')
        instalar = QPushButton('Instalar bc250-detect')
        instalar.clicked.connect(v.instalar_cpu_oc)
        head.addWidget(title)
        head.addWidget(hint)
        head.addStretch(1)
        head.addWidget(instalar)
        pl.addLayout(head)

        texto_cpu = v.t('Bloqueado por seguridad: maximo 4000 MHz y 1275 mV. El repo advierte que subir frecuencia sin undervolt puede dañar o brickear la placa; no se instala servicio CPU.')
        info_cpu = v.t('Mas informacion CPU:')
        aviso = QLabel(f'{texto_cpu} {info_cpu} <a href="https://github.com/bc250-collective/bc250_smu_oc">bc250-collective/bc250_smu_oc</a>')
        aviso.setObjectName('WarningTextCompact')
        aviso.setWordWrap(True)
        aviso.setOpenExternalLinks(True)
        aviso.setTextFormat(Qt.TextFormat.RichText)
        pl.addWidget(aviso)

        perfil_box = QFrame()
        perfil_box.setObjectName('InfoBox')
        perfil_l = QVBoxLayout(perfil_box)
        perfil_l.setContentsMargins(8, 7, 8, 7)
        perfil_l.setSpacing(6)
        presets = [
            ('Eficiente', '3500 MHz / 1000 mV', 3500, 1000, 90),
            ('Placa media', '3550 MHz / 1050 mV', 3550, 1050, 90),
            ('Balance', '3700 MHz / 1150 mV', 3700, 1150, 90),
            ('Punto medio', '3850 MHz / 1150 mV', 3850, 1150, 90),
            ('Max seguro UI', '4000 MHz / 1275 mV', 4000, 1275, 90),
        ]
        v.cpu_preset_buttons = []
        etiqueta_perfiles = QLabel('Presets')
        etiqueta_perfiles.setObjectName('SectionTitle')
        perfil_l.addWidget(etiqueta_perfiles)
        preset_grid = QGridLayout()
        preset_grid.setContentsMargins(0, 0, 0, 0)
        preset_grid.setHorizontalSpacing(6)
        preset_grid.setVerticalSpacing(6)
        for indice, (nombre, detalle, frecuencia, vid, temp) in enumerate(presets):
            card = QFrame()
            card.setObjectName('DetailChip')
            card.setMinimumHeight(68)
            card.setMaximumHeight(74)
            card.setMinimumWidth(205)
            card_l = QHBoxLayout(card)
            card_l.setContentsMargins(9, 7, 9, 7)
            card_l.setSpacing(7)
            textos = QVBoxLayout()
            textos.setContentsMargins(0, 0, 0, 0)
            textos.setSpacing(2)
            nombre_lbl = QLabel(v.t(nombre))
            nombre_lbl.setObjectName('SectionTitle')
            detalle_lbl = QLabel(v.t(detalle))
            detalle_lbl.setObjectName('Muted')
            boton = QPushButton(f'{v.t("Aplicar")} {frecuencia}')
            boton.setObjectName('ApplyButton' if frecuencia < 4000 else 'DangerButton')
            boton.setMinimumHeight(34)
            boton.setMinimumWidth(102)
            boton.setMaximumWidth(112)
            boton.setToolTip(f'{v.t(nombre)}: {frecuencia} MHz / {vid} mV / {temp} C')
            boton.clicked.connect(lambda _=False, f=frecuencia, mv=vid, t=temp: v.aplicar_cpu_oc(f, mv, t))
            v.cpu_preset_buttons.append(boton)
            textos.addWidget(nombre_lbl)
            textos.addWidget(detalle_lbl)
            card_l.addLayout(textos, 1)
            card_l.addWidget(boton)
            preset_grid.addWidget(card, 0, indice)
        perfil_l.addLayout(preset_grid)
        pl.addWidget(perfil_box)

        custom = QFrame()
        custom.setObjectName('InfoBox')
        custom.setMinimumHeight(94)
        custom_l = QVBoxLayout(custom)
        custom_l.setContentsMargins(10, 8, 10, 8)
        custom_l.setSpacing(7)
        custom_head = QHBoxLayout()
        custom_title = QLabel('Personalizado')
        custom_title.setObjectName('SectionTitle')
        custom_hint = QLabel('Ajusta segun cada placa. Prueba escalado y detente ante congelamientos.')
        custom_hint.setObjectName('Muted')
        custom_hint.setWordWrap(True)
        custom_head.addWidget(custom_title)
        custom_head.addWidget(custom_hint, 1)
        custom_l.addLayout(custom_head)
        custom_controls = QHBoxLayout()
        custom_controls.setSpacing(8)
        v.cpu_custom_enable = QCheckBox('Habilitar personalizado')
        v.cpu_custom_freq = QSpinBox()
        v.cpu_custom_freq.setRange(3000, 4000)
        v.cpu_custom_freq.setSingleStep(50)
        v.cpu_custom_freq.setSuffix(' MHz')
        v.cpu_custom_freq.setValue(3550)
        v.cpu_custom_freq.setMinimumWidth(112)
        v.cpu_custom_vid = QSpinBox()
        v.cpu_custom_vid.setRange(900, 1275)
        v.cpu_custom_vid.setSingleStep(25)
        v.cpu_custom_vid.setSuffix(' mV')
        v.cpu_custom_vid.setValue(1050)
        v.cpu_custom_vid.setMinimumWidth(105)
        v.cpu_custom_temp = QSpinBox()
        v.cpu_custom_temp.setRange(70, 90)
        v.cpu_custom_temp.setSingleStep(5)
        v.cpu_custom_temp.setSuffix(' C')
        v.cpu_custom_temp.setValue(90)
        v.cpu_custom_temp.setMinimumWidth(85)
        v.cpu_custom_apply = QPushButton('Aplicar personalizado')
        v.cpu_custom_apply.setObjectName('DangerButton')
        v.cpu_custom_apply.clicked.connect(v.aplicar_cpu_oc_personalizado)
        v.cpu_custom_enable.stateChanged.connect(v.actualizar_cpu_custom_ui)
        custom_controls.addWidget(v.cpu_custom_enable)
        custom_controls.addStretch(1)
        custom_controls.addWidget(v.cpu_custom_freq)
        custom_controls.addWidget(v.cpu_custom_vid)
        custom_controls.addWidget(v.cpu_custom_temp)
        custom_controls.addWidget(v.cpu_custom_apply)
        custom_l.addLayout(custom_controls)
        v.actualizar_cpu_custom_ui()
        pl.addWidget(custom)

        layout.addWidget(panel)

        persistencia = QFrame()
        persistencia.setObjectName('InfoBox')
        persist_l = QVBoxLayout(persistencia)
        persist_l.setContentsMargins(10, 8, 10, 8)
        persist_l.setSpacing(8)
        persist_head = QHBoxLayout()
        persist_title = QLabel('Persistencia avanzada')
        persist_title.setObjectName('SectionTitle')
        persist_hint = QLabel('Instala el ultimo overclock.conf probado como servicio systemd. Solo para configuraciones ya estables.')
        persist_hint.setObjectName('Muted')
        persist_hint.setWordWrap(True)
        persist_btn = QPushButton('Hacer persistente ultimo OC')
        persist_btn.setObjectName('DangerButton')
        persist_btn.clicked.connect(v.aplicar_cpu_oc_persistente)
        v.btn_cpu_persistente = persist_btn
        status_btn = QPushButton('Ver status')
        status_btn.clicked.connect(v.actualizar_cpu_oc_persistente_status)
        desactivar_btn = QPushButton('Desactivar servicio')
        desactivar_btn.setObjectName('DangerButton')
        desactivar_btn.clicked.connect(v.desactivar_cpu_oc_persistente)
        v.btn_cpu_persist_status = status_btn
        v.btn_cpu_persist_desactivar = desactivar_btn
        persist_head.addWidget(persist_title)
        persist_head.addWidget(persist_hint, 1)
        persist_head.addWidget(status_btn)
        persist_head.addWidget(desactivar_btn)
        persist_head.addWidget(persist_btn)
        persist_l.addLayout(persist_head)

        persist_status = QGridLayout()
        persist_status.setContentsMargins(0, 0, 0, 0)
        persist_status.setHorizontalSpacing(8)
        items_status = [
            ('Servicio', 'cpu_persist_servicio_valor', 'cpu_persist_servicio_detalle'),
            ('Estado', 'cpu_persist_estado_valor', 'cpu_persist_estado_detalle'),
            ('Config', 'cpu_persist_config_valor', 'cpu_persist_config_detalle'),
        ]
        for i, (titulo_status, attr_valor, attr_detalle) in enumerate(items_status):
            item = QFrame()
            item.setObjectName('DetailChip')
            item_l = QVBoxLayout(item)
            item_l.setContentsMargins(9, 6, 9, 6)
            item_l.setSpacing(2)
            etiqueta = QLabel(titulo_status)
            etiqueta.setObjectName('Muted')
            valor = QLabel('--')
            valor.setObjectName('DetailValue')
            detalle = QLabel('Pulsa Ver status')
            detalle.setObjectName('Muted')
            detalle.setWordWrap(True)
            setattr(v, attr_valor, valor)
            setattr(v, attr_detalle, detalle)
            item_l.addWidget(etiqueta)
            item_l.addWidget(valor)
            item_l.addWidget(detalle)
            persist_status.addWidget(item, 0, i)
        persist_l.addLayout(persist_status)
        layout.addWidget(persistencia)

        info = QFrame()
        info.setObjectName('BcDetailPanel')
        il = QGridLayout(info)
        il.setContentsMargins(12, 10, 12, 10)
        il.setHorizontalSpacing(8)
        il.setVerticalSpacing(7)
        detalles = [
            ('Comando', 'bc250-detect --frequency MHz --vid mV --temp C --keep'),
            ('No persistente', 'No ejecuta bc250-apply --install ni systemctl enable bc250-smu-oc.'),
            ('Techo UI', '4000 MHz / 1275 mV / 90 C'),
            ('Regla practica', 'Si crashea, sube voltaje con cuidado o baja frecuencia; cada BC250 es distinta.'),
        ]
        for i, (titulo, texto) in enumerate(detalles):
            item = QFrame()
            item.setObjectName('DetailChip')
            dl = QVBoxLayout(item)
            dl.setContentsMargins(9, 6, 9, 6)
            etiqueta = QLabel(titulo)
            etiqueta.setObjectName('Muted')
            valor = QLabel(texto)
            valor.setObjectName('DetailValue')
            valor.setWordWrap(True)
            dl.addWidget(etiqueta)
            dl.addWidget(valor)
            il.addWidget(item, i // 2, i % 2)
        layout.addWidget(info)

        consola = QFrame()
        consola.setObjectName('BcDetailPanel')
        cl = QVBoxLayout(consola)
        cl.setContentsMargins(12, 10, 12, 10)
        cl.setSpacing(7)
        ch = QHBoxLayout()
        ct = QLabel('Consola CPU OC')
        ct.setObjectName('SectionTitle')
        cd = QLabel('Salida del proceso bc250-detect dentro de la aplicacion.')
        cd.setObjectName('Muted')
        limpiar = QPushButton('Limpiar consola')
        limpiar.clicked.connect(lambda: v.cpu_oc_console.clear())
        ch.addWidget(ct)
        ch.addWidget(cd)
        ch.addStretch(1)
        ch.addWidget(limpiar)
        cl.addLayout(ch)
        v.cpu_oc_console = QPlainTextEdit()
        v.cpu_oc_console.setObjectName('TerminalText')
        v.cpu_oc_console.setReadOnly(True)
        v.cpu_oc_console.setMinimumHeight(170)
        v.cpu_oc_console.setPlainText('La salida de CPU OC aparecera aqui.')
        cl.addWidget(v.cpu_oc_console)
        layout.addWidget(consola)

        return self._panel_con_scroll(page)


    def _panel_40cu(self):
        v = self.vista
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(8)

        texto_40cu = v.t('40CU live-manager permite enrutar WGP/CU en vivo con UMR. Puede subir consumo y temperatura. Recomendado: GPU 1500 MHz / 900 mV antes de probar.')
        info_40cu = v.t('Mas informacion 40CU:')
        aviso = QLabel(f'{texto_40cu} {info_40cu} <a href="https://github.com/WinnieLV/bc250-cu-live-manager">WinnieLV/bc250-cu-live-manager</a> · <a href="https://github.com/duggasco/bc250-40cu-unlock">duggasco/bc250-40cu-unlock</a>')
        aviso.setObjectName('WarningTextCompact')
        aviso.setWordWrap(True)
        aviso.setOpenExternalLinks(True)
        aviso.setTextFormat(Qt.TextFormat.RichText)
        layout.addWidget(aviso)

        estado = QFrame()
        estado.setObjectName('BcPanel')
        estado_l = QGridLayout(estado)
        estado_l.setContentsMargins(12, 10, 12, 10)
        estado_l.setHorizontalSpacing(8)
        estado_l.setVerticalSpacing(7)
        v.cu_estado_labels = {}
        campos = [
            ('manager', 'CU manager', 'WinnieLV/bc250-cu-live-manager'),
            ('umr', 'UMR', 'Acceso a registros AMD'),
            ('modo', 'Modo', 'Live temporal'),
            ('recomendado', 'Recomendacion', 'GPU 1500/900 antes de probar'),
        ]
        for i, (clave, titulo, detalle) in enumerate(campos):
            item = QFrame()
            item.setObjectName('DetailChip')
            il = QVBoxLayout(item)
            il.setContentsMargins(10, 7, 10, 7)
            il.setSpacing(2)
            nombre = QLabel(titulo)
            nombre.setObjectName('Muted')
            valor = QLabel('--')
            valor.setObjectName('DetailValue')
            valor.setWordWrap(True)
            sub = QLabel(detalle)
            sub.setObjectName('Muted')
            sub.setWordWrap(True)
            il.addWidget(nombre)
            il.addWidget(valor)
            il.addWidget(sub)
            v.cu_estado_labels[clave] = {'valor': valor, 'detalle': sub}
            estado_l.addWidget(item, 0, i)
        layout.addWidget(estado)

        acciones = QFrame()
        acciones.setObjectName('InfoBox')
        al = QHBoxLayout(acciones)
        al.setContentsMargins(12, 9, 12, 9)
        al.setSpacing(8)
        title = QLabel('Acciones 40CU')
        title.setObjectName('SectionTitle')
        gpu_safe = QPushButton('Aplicar GPU 1500 recomendado')
        gpu_safe.clicked.connect(lambda: v.aplicar_perfil_bc250(v.minimo_gpu_seleccionado(), 1500, 'Recomendado para 40CU'))
        activar = QPushButton('Activar 40CU')
        activar.setObjectName('DangerButton')
        activar.clicked.connect(lambda: v.ejecutar_cu_manager('enable40'))
        stock = QPushButton('Restaurar 24CU')
        stock.clicked.connect(lambda: v.ejecutar_cu_manager('stock'))
        servicio = QPushButton('Servicio / perfil custom')
        servicio.setToolTip('Abre el menu oficial para editar tabla, guardar perfil e instalar servicio')
        servicio.clicked.connect(lambda: v.ejecutar_cu_manager('menu'))
        umr = QPushButton('Instalar UMR')
        umr.clicked.connect(v.instalar_umr)
        for w in [title, gpu_safe, activar, stock, servicio, umr]:
            al.addWidget(w)
        al.addStretch(1)
        layout.addWidget(acciones)

        dashboard = QFrame()
        dashboard.setObjectName('BcDetailPanel')
        dl = QVBoxLayout(dashboard)
        dl.setContentsMargins(12, 10, 12, 10)
        dl.setSpacing(7)
        dh = QHBoxLayout()
        dt = QLabel('Dashboard 40CU live dispatch')
        dt.setObjectName('SectionTitle')
        dd = QLabel('Muestra el estado real de WGP/CU: D+, S+, D! y -- por fila SE/SH.')
        dd.setObjectName('Muted')
        refrescar = QPushButton('Refrescar dashboard')
        refrescar.clicked.connect(v.actualizar_dashboard_cu)
        dh.addWidget(dt)
        dh.addWidget(dd)
        dh.addStretch(1)
        dh.addWidget(refrescar)
        dl.addLayout(dh)
        v.cu_dashboard_text = QPlainTextEdit()
        v.cu_dashboard_text.setObjectName('TerminalText')
        v.cu_dashboard_text.setReadOnly(True)
        v.cu_dashboard_text.setMinimumHeight(245)
        v.cu_dashboard_text.setPlainText('Pulsa "Refrescar dashboard" para leer el dashboard real de bc250-cu-live-manager.')
        dl.addWidget(v.cu_dashboard_text, 1)
        layout.addWidget(dashboard, 1)
        return self._panel_con_scroll(page)
