from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QCheckBox, QComboBox, QFrame, QGridLayout, QHBoxLayout, QHeaderView, QLabel,
    QPlainTextEdit, QPushButton, QScrollArea, QSizePolicy, QSlider, QSpinBox, QTableWidget,
    QVBoxLayout, QWidget
)


from mvc.View.Componentes.componentes import MetricStrip


class FanFrame:
    def __init__(self, vista):
        self.vista = vista
        self.contenedor = self._forms()

    def _forms(self):
        v = self.vista
        tr = v.t
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(10)
        top = QHBoxLayout()
        title_box = QVBoxLayout()
        page_title = QLabel(tr('Ventiladores'))
        page_title.setObjectName('PageTitle')
        page_subtitle = QLabel(tr('Monitor y control experimental para el conector de ventilador de la BC-250.'))
        page_subtitle.setObjectName('Muted')
        page_subtitle.setWordWrap(True)
        title_box.addWidget(page_title)
        title_box.addWidget(page_subtitle)
        v.fan_status_pill = QLabel('PWM --')
        v.fan_status_pill.setObjectName('StatusBox')
        v.fan_status_pill.setMinimumWidth(130)
        v.fan_status_pill.setAlignment(Qt.AlignmentFlag.AlignCenter)
        top.addLayout(title_box, 1)
        top.addWidget(v.fan_status_pill)
        layout.addLayout(top)

        scroll = QScrollArea()
        scroll.setObjectName('FlatScroll')
        scroll.setWidgetResizable(True)
        outer = QWidget()
        outer.setObjectName('ScrollPage')
        body = QVBoxLayout(outer)
        body.setContentsMargins(0, 0, 0, 0)
        body.setSpacing(10)

        monitor = QFrame()
        monitor.setObjectName('BcHero')
        monitor_l = QVBoxLayout(monitor)
        monitor_l.setContentsMargins(12, 8, 12, 8)
        monitor_l.setSpacing(5)
        header = QHBoxLayout()
        titulo = QLabel(tr('Monitor ventiladores'))
        titulo.setObjectName('SectionTitle')
        subtitulo = QLabel(tr('RPM principal, porcentaje de velocidad, temperaturas y frecuencias en vivo.'))
        subtitulo.setObjectName('Muted')
        subtitulo.setWordWrap(True)
        btn_pwm_top = QPushButton(tr('Preparar PWM ventilador'))
        btn_pwm_top.clicked.connect(v.preparar_fan_pwm)
        btn_status_top = QPushButton(tr('Status chip NCT'))
        btn_status_top.clicked.connect(v.mostrar_status_chip_fan)
        btn_disable_pwm = QPushButton(tr('Desactivar PWM fan'))
        btn_disable_pwm.setObjectName('DangerButton')
        btn_disable_pwm.clicked.connect(v.desactivar_fan_pwm)
        header.addWidget(titulo)
        header.addWidget(subtitulo, 1)
        header.addWidget(btn_pwm_top)
        header.addWidget(btn_status_top)
        header.addWidget(btn_disable_pwm)
        monitor_l.addLayout(header)

        grid = QGridLayout()
        grid.setSpacing(6)
        v.fan_rpm_main = MetricStrip(tr('RPM ventilador'), '#22d3ee')
        v.fan_speed_percent = MetricStrip(tr('Velocidad'), '#3b82f6')
        v.fan_cpu_temp = MetricStrip('CPU temp', '#f97316')
        v.fan_gpu_temp = MetricStrip('GPU temp', '#ec4899')
        v.fan_cpu_mhz = MetricStrip('CPU MHz', '#2563eb')
        v.fan_gpu_sclk = MetricStrip('GPU SCLK', '#8b5cf6')
        v.fan_driver_status = MetricStrip('Driver', '#10b981')
        v.fan_pwm_status = MetricStrip('PWM control', '#10b981')
        cards = [
            v.fan_rpm_main, v.fan_speed_percent, v.fan_cpu_temp, v.fan_gpu_temp,
            v.fan_cpu_mhz, v.fan_gpu_sclk, v.fan_driver_status, v.fan_pwm_status,
        ]
        for idx, card in enumerate(cards):
            card.spark.setVisible(False)
            card.detalle.setFixedHeight(15)
            card.setMaximumHeight(58)
            card.setMinimumWidth(0)
            card.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
            grid.addWidget(card, idx // 4, idx % 4)
        monitor_l.addLayout(grid)
        body.addWidget(monitor)

        manual = QFrame()
        manual.setObjectName('BcPanel')
        ml = QVBoxLayout(manual)
        ml.setContentsMargins(12, 10, 12, 10)
        ml.setSpacing(8)
        manual_head = QHBoxLayout()
        manual_title = QLabel(tr('Control de velocidad del ventilador'))
        manual_title.setObjectName('SectionTitleCompact')
        hint = QLabel(tr('Canal recomendado: Pump Fan / J4003 Fan 1. Usa porcentaje real de 0 a 100 y prueba cambios graduales.'))
        hint.setObjectName('Muted')
        hint.setWordWrap(True)
        manual_head.addWidget(manual_title)
        manual_head.addWidget(hint, 1)
        ml.addLayout(manual_head)

        control_row = QHBoxLayout()
        control_row.setSpacing(8)

        selector_card = QFrame()
        selector_card.setObjectName('DetailChip')
        selector_l = QHBoxLayout(selector_card)
        selector_l.setContentsMargins(10, 7, 10, 7)
        selector_l.setSpacing(8)
        selector_title = QLabel(tr('Canal'))
        selector_title.setObjectName('SectionTitleCompact')
        v.fan_pwm_combo = QComboBox()
        v.fan_pwm_combo.setObjectName('RiskCombo')
        v.fan_pwm_combo.setMinimumWidth(210)
        v.fan_pwm_combo.setMaximumWidth(290)
        v.fan_pwm_combo.currentIndexChanged.connect(v.actualizar_valor_pwm_seleccionado)
        selector_l.addWidget(selector_title)
        selector_l.addWidget(v.fan_pwm_combo)
        control_row.addWidget(selector_card, 1)

        presets_card = QFrame()
        presets_card.setObjectName('DetailChip')
        presets_l = QHBoxLayout(presets_card)
        presets_l.setContentsMargins(10, 7, 10, 7)
        presets_l.setSpacing(6)
        presets_title = QLabel(tr('Perfiles'))
        presets_title.setObjectName('SectionTitleCompact')
        presets_l.addWidget(presets_title)
        v.fan_speed_buttons = []
        for texto, valor in [('45%', 45), ('60%', 60), ('70%', 70), ('100%', 100)]:
            btn = QPushButton(texto)
            btn.setObjectName('ApplyButton')
            btn.setMinimumHeight(30)
            btn.setMaximumWidth(58)
            btn.clicked.connect(lambda _=False, p=valor: v.aplicar_fan_pwm_porcentaje(p))
            v.fan_speed_buttons.append(btn)
            presets_l.addWidget(btn)
        control_row.addWidget(presets_card, 1)

        slider_card = QFrame()
        slider_card.setObjectName('DetailChip')
        slider_l = QHBoxLayout(slider_card)
        slider_l.setContentsMargins(10, 7, 10, 7)
        slider_l.setSpacing(8)
        slider_title = QLabel(tr('Velocidad'))
        slider_title.setObjectName('SectionTitleCompact')
        v.fan_speed_slider = QSlider(Qt.Orientation.Horizontal)
        v.fan_speed_slider.setRange(0, 100)
        v.fan_speed_slider.setValue(70)
        v.fan_speed_slider.setTickPosition(QSlider.TickPosition.NoTicks)
        v.fan_speed_slider.setSingleStep(1)
        v.fan_speed_slider.setPageStep(5)
        v.fan_speed_slider.setTracking(True)
        v.fan_speed_slider.setMinimumWidth(180)
        v.fan_pwm_valor = QSpinBox()
        v.fan_pwm_valor.setObjectName('PercentSpin')
        v.fan_pwm_valor.setRange(0, 100)
        v.fan_pwm_valor.setValue(70)
        v.fan_pwm_valor.setSuffix(' %')
        v.fan_pwm_valor.setMinimumWidth(96)
        v.fan_pwm_valor.setMaximumWidth(106)
        v.fan_pwm_valor.setMinimumHeight(30)
        v.fan_speed_slider.valueChanged.connect(v.fan_pwm_valor.setValue)
        v.fan_pwm_valor.valueChanged.connect(v.fan_speed_slider.setValue)
        v.fan_pwm_apply = QPushButton(tr('Aplicar'))
        v.fan_pwm_apply.setObjectName('DangerButton')
        v.fan_pwm_apply.setMinimumHeight(30)
        v.fan_pwm_apply.setMaximumWidth(96)
        v.fan_pwm_apply.clicked.connect(lambda: v.aplicar_fan_pwm_manual())
        slider_l.addWidget(slider_title)
        slider_l.addWidget(v.fan_speed_slider, 1)
        slider_l.addWidget(v.fan_pwm_valor)
        slider_l.addWidget(v.fan_pwm_apply)
        control_row.addWidget(slider_card, 2)
        ml.addLayout(control_row)
        body.addWidget(manual)

        curva = QFrame()
        curva.setObjectName('BcPanel')
        cl = QVBoxLayout(curva)
        cl.setContentsMargins(12, 10, 12, 10)
        cl.setSpacing(8)
        curva_head = QHBoxLayout()
        curva_title = QLabel(tr('Curva por temperatura GPU'))
        curva_title.setObjectName('SectionTitleCompact')
        curva_hint = QLabel(tr('Curva guardada: funciona con la app abierta y tambien con el daemon opcional activo.'))
        curva_hint.setObjectName('Muted')
        curva_hint.setWordWrap(True)
        v.fan_curve_enable = QCheckBox(tr('Activar curva automatica GPU'))
        v.fan_curve_enable.blockSignals(True)
        v.fan_curve_enable.setChecked(bool(getattr(v, 'fan_curve_edicion_activa', getattr(v, 'fan_curve_activa', False))))
        v.fan_curve_enable.blockSignals(False)
        v.fan_curve_enable.stateChanged.connect(v.validar_fan_curve_toggle)
        curva_head.addWidget(curva_title)
        curva_head.addWidget(curva_hint, 1)
        curva_head.addWidget(v.fan_curve_enable)
        cl.addLayout(curva_head)

        preset_row = QHBoxLayout()
        preset_row.setSpacing(8)
        preset_card = QFrame()
        preset_card.setObjectName('DetailChip')
        preset_l = QHBoxLayout(preset_card)
        preset_l.setContentsMargins(10, 7, 10, 7)
        preset_l.setSpacing(6)
        preset_title = QLabel(tr('Presets curva'))
        preset_title.setObjectName('SectionTitleCompact')
        preset_l.addWidget(preset_title)
        v.fan_curve_preset_buttons = []
        for texto, clave in [(tr('Silenciosa'), 'silent'), (tr('Balanceada'), 'balanced'), (tr('Fria'), 'cool')]:
            btn = QPushButton(texto)
            btn.setObjectName('ApplyButton')
            btn.setMinimumHeight(30)
            btn.setMaximumWidth(110)
            btn.clicked.connect(lambda _=False, k=clave: v.aplicar_preset_curva_fan(k))
            v.fan_curve_preset_buttons.append(btn)
            preset_l.addWidget(btn)
        preset_row.addWidget(preset_card, 0)

        status_card = QFrame()
        status_card.setObjectName('DetailChip')
        status_l = QHBoxLayout(status_card)
        status_l.setContentsMargins(10, 7, 10, 7)
        status_l.setSpacing(10)
        v.fan_curve_summary = QLabel('')
        v.fan_curve_summary.setObjectName('Muted')
        v.fan_curve_summary.setWordWrap(True)
        v.fan_last_pwm_label = QLabel('')
        v.fan_last_pwm_label.setObjectName('Muted')
        v.fan_last_pwm_label.setWordWrap(True)
        status_l.addWidget(v.fan_curve_summary, 2)
        status_l.addWidget(v.fan_last_pwm_label, 1)
        preset_row.addWidget(status_card, 1)
        cl.addLayout(preset_row)

        puntos = QHBoxLayout()
        puntos.setSpacing(8)
        v.fan_curve_t1 = QSpinBox(); v.fan_curve_t1.setRange(30, 95); v.fan_curve_t1.setValue(v.fan_curve_valor('t1', 50)); v.fan_curve_t1.setSuffix(' C')
        v.fan_curve_s1 = QSpinBox(); v.fan_curve_s1.setRange(0, 100); v.fan_curve_s1.setValue(v.fan_curve_valor('s1', 70)); v.fan_curve_s1.setSuffix(' %')
        v.fan_curve_t2 = QSpinBox(); v.fan_curve_t2.setRange(30, 95); v.fan_curve_t2.setValue(v.fan_curve_valor('t2', 65)); v.fan_curve_t2.setSuffix(' C')
        v.fan_curve_s2 = QSpinBox(); v.fan_curve_s2.setRange(0, 100); v.fan_curve_s2.setValue(v.fan_curve_valor('s2', 100)); v.fan_curve_s2.setSuffix(' %')
        v.fan_curve_t3 = QSpinBox(); v.fan_curve_t3.setRange(30, 95); v.fan_curve_t3.setValue(v.fan_curve_valor('t3', 70)); v.fan_curve_t3.setSuffix(' C')
        v.fan_curve_s3 = QSpinBox(); v.fan_curve_s3.setRange(0, 100); v.fan_curve_s3.setValue(v.fan_curve_valor('s3', 100)); v.fan_curve_s3.setSuffix(' %')
        for spin in [v.fan_curve_t1, v.fan_curve_s1, v.fan_curve_t2, v.fan_curve_s2, v.fan_curve_t3, v.fan_curve_s3]:
            spin.setObjectName('PercentSpin')
            spin.valueChanged.connect(v.guardar_config_fan_curve)
        for titulo_punto, temp, speed in [
            (tr('Punto 1'), v.fan_curve_t1, v.fan_curve_s1),
            (tr('Punto 2'), v.fan_curve_t2, v.fan_curve_s2),
            (tr('Punto 3'), v.fan_curve_t3, v.fan_curve_s3),
        ]:
            chip = QFrame()
            chip.setObjectName('DetailChip')
            chip.setMaximumHeight(58)
            chip_l = QHBoxLayout(chip)
            chip_l.setContentsMargins(10, 7, 10, 7)
            chip_l.setSpacing(6)
            label = QLabel(titulo_punto)
            label.setObjectName('SectionTitleCompact')
            for spin in [temp, speed]:
                spin.setMaximumWidth(116)
                spin.setMinimumWidth(104)
                spin.setMinimumHeight(30)
            chip_l.addWidget(label)
            chip_l.addWidget(temp)
            chip_l.addWidget(speed)
            puntos.addWidget(chip)
        puntos.addStretch(1)
        v.fan_curve_apply = QPushButton(tr('Aplicar curva ahora'))
        v.fan_curve_apply.setMinimumHeight(34)
        v.fan_curve_apply.setMaximumWidth(160)
        v.fan_curve_apply.clicked.connect(v.aplicar_curva_fan_gpu_manual)
        puntos.addWidget(v.fan_curve_apply)
        cl.addLayout(puntos)
        v.actualizar_controles_curva_fan()
        body.addWidget(curva)

        tabla_box = QFrame()
        tabla_box.setObjectName('BcPanel')
        tl = QVBoxLayout(tabla_box)
        tl.setContentsMargins(12, 10, 12, 12)
        header = QHBoxLayout()
        titulo = QLabel(tr('Canales visibles'))
        titulo.setObjectName('SectionTitle')
        subtitulo = QLabel(tr('Se muestran PWM 2, 1 y 3 para evitar ruido visual. Los hubs/splitters comparten control PWM y normalmente reportan una sola RPM.'))
        subtitulo.setObjectName('Muted')
        subtitulo.setWordWrap(True)
        rutas_btn = QPushButton(tr('Informe rutas PWM'))
        rutas_btn.clicked.connect(v.mostrar_informe_rutas_pwm)
        header.addWidget(titulo)
        header.addWidget(subtitulo, 1)
        header.addWidget(rutas_btn)
        tl.addLayout(header)
        tabla = QTableWidget(0, 5)
        v.fan_table = tabla
        v.configurar_tabla(tabla)
        tabla.setHorizontalHeaderLabels([v.t('Canal'), v.t('Nombre'), v.t('RPM'), v.t('Velocidad'), v.t('Permiso')])
        tabla.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        tabla.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
        tabla.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
        tabla.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
        tabla.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
        tabla.verticalHeader().setDefaultSectionSize(30)
        tabla.setMaximumHeight(150)
        tl.addWidget(tabla)
        body.addWidget(tabla_box)

        aviso = QLabel(
            tr('Aviso: primero prepara PWM ventilador. Cambia la velocidad poco a poco y mira las temperaturas. ') +
            tr('Con splitter/hub PWM normalmente se controla todo junto y solo se lee una senal RPM. ') +
            tr('Mas informacion:') + ' <a href="https://elektricm.github.io/amd-bc250-docs/system/sensors/">BC250 Sensors Guide</a> - '
            '<a href="https://github.com/Fred78290/nct6687d">nct6687d</a>'
        )
        aviso.setObjectName('WarningTextCompact')
        aviso.setWordWrap(True)
        aviso.setOpenExternalLinks(True)
        body.addWidget(aviso)

        detalle_box = QFrame()
        detalle_box.setObjectName('BcPanel')
        dl = QVBoxLayout(detalle_box)
        dl.setContentsMargins(12, 10, 12, 12)
        det_title = QLabel(tr('Diagnostico'))
        det_title.setObjectName('SectionTitle')
        v.fan_detalle = QPlainTextEdit()
        v.fan_detalle.setObjectName('TerminalText')
        v.fan_detalle.setReadOnly(True)
        v.fan_detalle.setMinimumHeight(150)
        dl.addWidget(det_title)
        dl.addWidget(v.fan_detalle)
        body.addWidget(detalle_box)
        body.addStretch(1)

        scroll.setWidget(outer)
        layout.addWidget(scroll, 1)
        return page
