#!/usr/bin/env python3
"""Generate the copies of the shared contract the other two processes read.

``src/bc250cc/shared/contract.py`` is canon, and the desktop imports it
normally. The two root processes cannot: the privileged helpers run under
``python3 -I`` and the Decky backend only receives the files its installer
stages. So they read a generated module at a fixed absolute path instead.

The artefacts are **committed**, not produced at install time. Three reasons:

* On rpm-ostree ``/usr`` is baked by the RPM, so there is no install step that
  could write there.
* ``scripts/install-decky-quick-access.sh`` verifies the installed tree against
  the source tree with ``cmp -s``, which needs a byte-identical file to exist
  in the checkout already.
* Committing means the file inherits every existing mechanism for free: the
  ``cp -a privileged/`` in the package staging script, the ``install -Dm644``
  loop in the local installer, and that installer's rollback transaction. The
  repository already commits ``dist/index.js`` for the same reason.

A test re-runs this generator in memory and byte-compares, so a contract edit
without a regeneration fails rather than shipping a stale copy.

    python3 scripts/development/generate_contract.py [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

PYTHON_ARTEFACT = ROOT / "privileged" / "lib" / "bc250_contract.py"
PANEL_ARTEFACT = (
    ROOT
    / "integrations"
    / "decky"
    / "bc250-quick-access"
    / "src"
    / "generated"
    / "error_catalog.json"
)

HEADER = '''"""Generated from src/bc250cc/shared/contract.py. Do not edit.

Run scripts/development/generate_contract.py after changing the contract; a
test byte-compares this file against the generator's output.

This module is loaded by absolute path and executed as root by helpers running
under ``python3 -I``. It therefore imports nothing, calls nothing at module
scope, and contains only data and pure functions.
"""

from __future__ import annotations

'''

# Names emitted as plain literals, in this order.
DATA_NAMES = (
    "CONTRACT_REVISION",
    "QUICK_ACCESS_PROTOCOL",
    "CPU_SMU_HELPER_PROTOCOL",
    "GOVERNOR_CONFIG_PROTOCOL",
    "STEAMOS_GAME_HELPER_PROTOCOL",
    "QUICK_ACCESS_CU_RUNTIME_SCHEMA",
    "CPU_FREQUENCY_RANGE",
    "CPU_FREQUENCY_STEP_MHZ",
    "CPU_SCALE_RANGE",
    "CPU_TEMPERATURE_RANGE",
    "CPU_VID_LIMIT_MV",
    "CPU_VID_RANGE",
    "CPU_VID_STEP_MV",
    "CPU_VID_MODEL",
    "CU_TARGET_RANGE",
    "CU_TARGET_STEP",
    "OBERON_REFERENCE_VOLTAGE_MV",
    "OBERON_CONSERVATIVE_PROFILES",
    "OBERON_BENCHMARK_PROFILE",
    "OBERON_LEGACY_BENCHMARK_PROFILE",
    "OBERON_DESKTOP_PROFILES",
    "OBERON_ACCEPTED_PROFILES",
    "DESKTOP_FAN_PRESET_PERCENT",
    "DESKTOP_FAN_CHANNEL_RANGE",
    "QUICK_ACCESS_FAN_PRESET_DUTY",
    "QUICK_ACCESS_FAN_CHANNELS",
    "QUICK_ACCESS_FAN_PERCENT_RANGE",
    "QUICK_ACCESS_FAN_PERCENT_STEP",
)

# Functions copied verbatim, so the arithmetic has exactly one definition.
FUNCTION_NAMES = ("cpu_frequency_ladder", "cpu_vid_ladder", "estimated_vid", "cu_targets")


def _python_artefact() -> str:
    from bc250cc.shared import contract

    source = (ROOT / "src" / "bc250cc" / "shared" / "contract.py").read_text(encoding="utf-8")
    lines = [HEADER]
    for name in DATA_NAMES:
        lines.append(f"{name} = {getattr(contract, name)!r}\n")
    for name in FUNCTION_NAMES:
        start = source.index(f"def {name}(")
        end = source.index("\n\n\n", start)
        lines.append("\n\n" + source[start:end] + "\n")
    return "".join(lines)


def _panel_artefact() -> str:
    """Codes, markers and statuses for the panel — never the wording.

    The sentences are already translated on both sides; duplicating them here
    would create a third set to keep in step. The array is emitted in the
    catalogue's own longest-marker-first order so the TypeScript cannot get the
    tie-break wrong without knowing the rule.
    """
    from bc250cc.shared import contract
    from bc250cc.shared.error_catalog import _CODES, _MARKERS_BY_LENGTH

    order = {id(entry): index for index, (_marker, entry) in enumerate(_MARKERS_BY_LENGTH)}
    payload = {
        "contract_revision": contract.CONTRACT_REVISION,
        "comment": "Generated by scripts/development/generate_contract.py. Do not edit.",
        "codes": [
            {
                "code": entry.code,
                "markers": list(entry.markers),
                "exit_statuses": list(entry.exit_statuses),
                "retryable": bool(entry.retryable),
            }
            for entry in sorted(_CODES, key=lambda item: order.get(id(item), len(order)))
        ],
        "markers_longest_first": [marker for marker, _entry in _MARKERS_BY_LENGTH],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def artefacts() -> dict[Path, str]:
    return {PYTHON_ARTEFACT: _python_artefact(), PANEL_ARTEFACT: _panel_artefact()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if an artefact is out of date instead of writing it",
    )
    arguments = parser.parse_args()

    stale: list[Path] = []
    for path, text in artefacts().items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == text:
            continue
        if arguments.check:
            stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        print("run scripts/development/generate_contract.py", file=sys.stderr)
        return 1
    if not arguments.check:
        print("up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
